### ISSUE TITLE
Proper versioning

### ISSUE THREAD

**Issue by amotl** [crate/cratedb-sqlparse#19]
We should also document somewhere (maybe in the README) the relation between the **cratedb-sqlparse** version  and the **CrateDB** version itself, also I would add a small note on the release notes.

_Originally posted by @surister in https://github.com/crate/cratedb-sqlparse/issues/3#issuecomment-2122215490_

**Comment by amotl** [comment]
> For Python package versioning, we are using the excellent [versioningit](https://pypi.org/project/versioningit/) to reduce maintenance overheads. For NPM packages, I can't discover a corresponding package or mechanism yet. So, as a start, using traditional tools like [npm-version](https://docs.npmjs.com/cli/commands/npm-version) will be good enough?

-- https://github.com/crate/cratedb-sqlparse/issues/5#issuecomment-2138185378

/cc @alexdametto

**Comment by surister** [comment]
Yes, I wouldn't complicate it any further, I'd propose to maintain a simple table in the readme like:
Also adding a line in every Github release specifing the CrateDB version the package was compiled for

|  npm version | github_tag  | CrateDB Version  |
|---|---|---|
|  0.0.3 | 0.0.3    | 5.7.1   |
| 0.0.2  | 0.0.2   | 5.6.4  |

**Comment by amotl** [comment]
What about my proposal at https://github.com/crate/cratedb-sqlparse/issues/19#issuecomment-2124663016, to not have any mapping table at all, just following the release numbering of the relevant upstream project, in this case, CrateDB?

**Comment by surister** [comment]
> What about my proposal at [#19 (comment)](https://github.com/crate/cratedb-sqlparse/issues/19#issuecomment-2124663016), to not have any mapping table at all, and just following the release numbering of the relevant upstream project instead, in this case, CrateDB?

The thing is that it more complex and we might need to keep our own versions, for instance having two releases compiled for 5.7.1 makes sense, since there are many features that we currently haven't implemented.

**Comment by amotl** [comment]
According to https://semver.org/, we could use a suffix [^1] to increase version numbers when needed, i.e. when needing to publish releases within the same cycle of CrateDB, without a version bump on it.

Examples:
- 5.6.4+000
- 5.7.1+000
- 5.7.1+001
- 5.7.1+002

[^1]: Build metadata MAY be denoted by appending a plus sign and a series of identifiers comprised of ASCII characters.

**Comment by surister** [comment]
For example: `5.7.1+001` has feature `a` and `5.7.1+002` has feature `a+1` breaking change, we'd still need to keep track of things somewhere so an user can pick between `001` and `002` right?

**Comment by amotl** [comment]
After shuffling a few ideas in a private conversation, we may turn my proposal around, use regular semver-based project versioning like any other reasonable project, and add the CrateDB version as a suffix, to spare mapping tables.

- 0.0.2+5.6.4
- 0.0.3+5.7.1
- 0.0.4+5.7.1

**Comment by proddata** [comment]
I think it is rather rare that a feature gets removed from the dialect, i.e. most versions should be backwards compatible. Forward compatibility seems to be a bigger issue. Generally I assume it would be fine to support the latest stable, however be aware that tools would potentially not be fully compatible with nightly CrateDB builds then.

**Comment by surister** [comment]
After reading Georg's comment and thinking about it, I changed my mind. I was mostly worried about backwards comparability, [cratedb-admin-alt](https://github.com/surister/cratedb-admin-alt) has been in CrateDB's 5.4 for a while and I have extensively used for >5.4 and never had any issue, it sort of make sense since our SQL is stable. 

So I wouldn't complicate it further, let's just keep a plain x.x.x semver versioning, and always build/support the latest CrateDB version.
