### ISSUE TITLE
Upload Python package to PyPI

### ISSUE THREAD

**Issue by surister** [crate/cratedb-sqlparse#3]
The Python variant of the package needs to be uploaded to PyPI.

**Comment by amotl** [comment]
We are running a few projects with valid and mature `pyproject.toml` configurations to ease uploading to PyPI. Let us know if we should contribute a corresponding piece here, to save you a few keystrokes.

**Comment by amotl** [comment]
Hi. I just wanted to have a look at packaging, but then, I discovered in [this documentation section](https://github.com/crate/cratedb-sqlparse#building-locally--using-a-different-cratedb-version), that the parser would actually not be part of the package by default, so it would not be usable right away for people having different expectations?

Let's look into this on behalf of an out-of-band sync, and report back later here about the outcome?

**Comment by surister** [comment]
Not part of the repo, we have to create the parser at packaging time so the packages are usable

**Comment by amotl** [comment]
Hi again. That patch brings a few things into place, in order to prepare packaging and publishing.

- GH-10

**Comment by amotl** [comment]
Because the JavaScript package was already at version 0.0.2, the repository has now been tagged with v0.0.2.
Based on that, and the previous improvements, the Python package has been published to PyPI now.

-- https://pypi.org/project/cratedb-sqlparse/

**Comment by surister** [comment]
Amazing, thanks for the help. 

We should also document somewhere (maybe in the README) the relation between the **cratedb-sqlparse** version  and the **CrateDB** version itself, also I would add a small note on the release notes.
