### ISSUE TITLE
Upload npm package

### ISSUE THREAD

**Issue by surister** [crate/cratedb-sqlparse#5]
The JavaScript variant of the package needs to be uploaded to the npm registry at npmjs.com.

**Comment by amotl** [comment]
That patch adds a corresponding CI/GHA configuration to validate the implementation by running corresponding software tests on CI.

- GH-20

**Comment by proddata** [comment]
This would be very handy if we go the route of direct cluster access via JWT and therefore would need to split queries in the console. https://github.com/crate/cloud/issues/1888

**Comment by amotl** [comment]
For Python package versioning, we are using the excellent versioningit. For NPM packages, I can't discover a corresponding package or mechanism yet. So, as a start, using traditional tools like [npm-version](https://docs.npmjs.com/cli/commands/npm-version) will be good enough?

**Comment by amotl** [comment]
Another bit of adjustments before package publishing, mostly about »naming things«.

- GH-24

**Comment by amotl** [comment]
An initial version of the package has been published. Thanks for your support, @alexdametto.

-- https://www.npmjs.com/package/@cratedb/cratedb-sqlparse
