### ISSUE TITLE
Only latest table name is saved

### ISSUE THREAD

**Issue by surister** [crate/cratedb-sqlparse#50]
Sql queries can have several schemas/table names.

```python
>>> stmt = sqlparse("""SELECT a FROM sys.t JOIN doc.b ON t.a = b.a""")[0]
>>> print(stmt.metadata)
Metadata(schema='doc', table_name= 'b', parameterized_properties={}, with_properties={})
```

`sys.t` table information is lost, it's easy to fix, the question is about the resulting API

`Metadata(schema=['sys', 'doc'], table_name=['t', 'b'], parameterized_properties={}, with_properties={})` would this be good enough, where schemas and table_name are ordered?

If no schema it'd be: 
`Metadata(schema=[None, 'doc'], table_name=['t', 'b'], parameterized_properties={}, with_properties={})`

Now that you are integrating into this, wdyt? @amotl

**Comment by amotl** [comment]
Thanks for your support. So, when looking at this...
```python
schema=['sys', 'doc'], table_name=['t', 'b']
```

... would I need to coalesce them together again to get a full-qualified table name?

**Comment by surister** [comment]
Maybe:

`Metadata(tables=[Table(schema='doc', name='t'), ...], parameterized_properties={}, with_properties={})` where the `Table` dataclass has some kind of `.quoted` so
```python
>>> t = Table(schema='doc', name='t')
>>> t.quoted
"doc"."t"
```

Would also enable new stuff in the future like aliases.

```python
>>> stmt = sqlparse('SELECT a FROM sys.t alias_a JOIN doc.b alias_b ON t.a = b.a')[0]
>>> t = stmt.tables[0]
>>> t
Table(schema='sys', name='t')
>>> t.quoted
"sys"."t"
>>> t.alias
{"alias_b": "sys"."t"}
```

**Comment by amotl** [comment]
OO FTW. Excellent, je vous remercie.

**Comment by amotl** [comment]
JFYI: Maybe CrateDB Toolkit's [quote_relation_name()](https://github.com/crate-workbench/cratedb-toolkit/blob/v0.0.14/cratedb_toolkit/util/database.py#L36-L66) function is helpful in any way? Please let me know, I planned to refactor it to sqlalchemy-cratedb earlier or later. If you would need it, it could happen earlier.
