### ISSUE TITLE
Migrate cratedb_sqlparse from javascript to typescript

### ISSUE THREAD

**Issue by alexdametto** [crate/cratedb-sqlparse#52]
Right now `cratedb_sqlparse` does not support typescript, so every typescript project that wants to use this library needs to define their own types, leading to possible type error(s). We should migrate it to typescript (since it is also compatible with plain javascript).

**Comment by surister** [comment]
Honestly I have never liked the typescript DX, I would much rather [generate the typescript types from javascript](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html), so users get the benefit of typescript and not port the project to ts.

Give me a few days while I finish the lats updates #38, I'll try to generate all the types, if I don't manage to create something that satisfy you, I'll give in and migrate to/learn typescript.
